// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TpServeur1.Models;

namespace TpServeur1.Migrations
{
    [DbContext(typeof(TpContext))]
    [Migration("20220419134628_MigImageBlob")]
    partial class MigImageBlob
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("TpServeur1.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TpServeur1.Models.Commande", b =>
                {
                    b.Property<int>("CommandeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserGuid")
                        .HasColumnType("text");

                    b.HasKey("CommandeID");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("TpServeur1.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("longblob");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TpServeur1.Models.ItemCommande", b =>
                {
                    b.Property<int>("ItemCommandeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CommandeID")
                        .HasColumnType("int");

                    b.Property<double>("MontantUnitaire")
                        .HasColumnType("double");

                    b.Property<int>("ProduitID")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("ItemCommandeID");

                    b.HasIndex("CommandeID");

                    b.HasIndex("ProduitID");

                    b.ToTable("ItemCommande");
                });

            modelBuilder.Entity("TpServeur1.Models.ItemPanier", b =>
                {
                    b.Property<int>("ItemPanierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PanierID")
                        .HasColumnType("int");

                    b.Property<int>("ProduitID")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("ItemPanierID");

                    b.HasIndex("PanierID");

                    b.HasIndex("ProduitID");

                    b.ToTable("ItemPanier");
                });

            modelBuilder.Entity("TpServeur1.Models.Panier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserGuid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Panier");
                });

            modelBuilder.Entity("TpServeur1.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<double>("Prix")
                        .HasColumnType("double");

                    b.Property<int>("QteInventaire")
                        .HasColumnType("int");

                    b.Property<int?>("Taille")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("ImageId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("TpServeur1.Models.ItemCommande", b =>
                {
                    b.HasOne("TpServeur1.Models.Commande", "Commande")
                        .WithMany("Items")
                        .HasForeignKey("CommandeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpServeur1.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("TpServeur1.Models.ItemPanier", b =>
                {
                    b.HasOne("TpServeur1.Models.Panier", "Panier")
                        .WithMany("ItemPanier")
                        .HasForeignKey("PanierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpServeur1.Models.Produit", "Produit")
                        .WithMany("ItemPanier")
                        .HasForeignKey("ProduitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("TpServeur1.Models.Produit", b =>
                {
                    b.HasOne("TpServeur1.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpServeur1.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Categorie");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TpServeur1.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("TpServeur1.Models.Commande", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TpServeur1.Models.Panier", b =>
                {
                    b.Navigation("ItemPanier");
                });

            modelBuilder.Entity("TpServeur1.Models.Produit", b =>
                {
                    b.Navigation("ItemPanier");
                });
#pragma warning restore 612, 618
        }
    }
}
